### PR TITLE
remove gravitational from our repo

### PR DESCRIPTION
**Pull request by vegichan**
Remove 3rd party library from our repo. Use a go dependency instead

### CODE REVIEW

**Comment by thebithead** [comment]
Did you run the System level E2E test (test/bin/nuodb_op_system_e2e.sh) with this change?  Can you put the test results in the Jira ticket?

**Comment by vegichan** [comment]
@thebithead  are those not being run automatically in Travis?

**Comment by thebithead** [comment]
You have to run them manually.  I wrote about this before.  Also the need to run on a real OCP cluster, not minikube.

**Comment by vegichan** [comment]
this is a logging library. Everything compiles as expected, what else is there to do?

**Comment by thebithead** [comment]
Other than recording the results of the system e2e test in the Jira, there is nothing else to do.

**Comment by vegichan** [comment]
thanks @thebithead

**Pull request merged**
